### ISSUE TITLE
Building issues - Xamarin.Forms.GoogleMaps directory empty

### ISSUE THREAD

**Issue by gnout** [mierzynskim/Xamarin.Forms.GoogleMaps.Clustering#5]
When downloading the repository as a zip, the directory "Xamarin.Forms.GoogleMaps.Clustering-master\src\Xamarin.Forms.GoogleMaps" is empty.

**Comment by leaguefun** [comment]
I fixed by using old-fashioned method ...
1. Download the source from -> https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps/tree/e55687253b13be542a583f605f8ccc538860feda
2. Unzip those file, and move all files within your "empty" folder, i.e. "Xamarin.Forms.GoogleMaps.Clustering-master\src\Xamarin.Forms.GoogleMaps"
3. Close the VS and reopen the solution

Hope it will have little help.

**Comment by mierzynskim** [comment]
Xamarin.Forms.GoogleMaps is added as a submodule so downloading it as a zip won't work in that case. Please clone the repository using git or use a nuget package I created https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps.Clustering
